PREFIX mu: <http://mu.semte.ch/application/>
PREFIX eurostat: <http://mu.semte.ch/eurostat/>

INSERT INTO <http://mu.semte.ch/eurostat/AHPD> {
  eurostat:product1 a eurostat:Product .
  eurostat:product1 mu:gtin "1230123" .
  eurostat:product1 mu:amount 8 .
  eurostat:product1 mu:description "coke a cola" .
  eurostat:product1 mu:class eurostat:class20203
}


INSERT INTO <http://mu.semte.ch/eurostat/ECOICOP> {
  eurostat:class20203 a eurostat:ECOICOP .
  eurostat:class20203 mu:name "rice" .
}